# Generated by Django 4.2.5 on 2023-09-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_bid_user_alter_bid_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.FloatField(),
        ),
    ]
