# Generated by Django 4.2.5 on 2023-09-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_bid_price_alter_listing_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
