# Generated by Django 4.2.5 on 2023-09-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_bid_price_alter_listing_starting_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
